"""atmos payment transactions + orders.payment_status

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-13

Yangi: payment_transactions jadvali, orders.payment_status ustuni.
orders.status uzunligi 16 → 32 (yangi 'pending_payment' qiymati uchun joy).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('atmos_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('atmos_success_trans_id', sa.BigInteger(), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('amount_tiyin', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('atmos_status_code', sa.String(length=16), nullable=True),
    sa.Column('atmos_status_message', sa.Text(), nullable=True),
    sa.Column('card_id', sa.String(length=64), nullable=True),
    sa.Column('ofd_url', sa.Text(), nullable=True),
    sa.Column('ofd_url_commission', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('callback_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_atmos_success_trans_id'), 'payment_transactions', ['atmos_success_trans_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_atmos_transaction_id'), 'payment_transactions', ['atmos_transaction_id'], unique=True)
    op.create_index(op.f('ix_payment_transactions_order_id'), 'payment_transactions', ['order_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.add_column('orders', sa.Column('payment_status', sa.String(length=32), server_default='pending', nullable=False))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('orders', 'payment_status')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_order_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_atmos_transaction_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_atmos_success_trans_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    # ### end Alembic commands ###
