"""bound cards (Atmos saqlangan kartalar)

Revision ID: 0003
Revises: 0002
Create Date: 2026-05-13

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bound_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_token', sa.String(length=255), nullable=True),
    sa.Column('bind_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('pan_masked', sa.String(length=32), nullable=True),
    sa.Column('expiry', sa.String(length=4), nullable=True),
    sa.Column('card_holder', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending_bind', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bound_cards_bind_transaction_id'), 'bound_cards', ['bind_transaction_id'], unique=True)
    op.create_index(op.f('ix_bound_cards_card_token'), 'bound_cards', ['card_token'], unique=True)
    op.create_index(op.f('ix_bound_cards_user_id'), 'bound_cards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bound_cards_user_id'), table_name='bound_cards')
    op.drop_index(op.f('ix_bound_cards_card_token'), table_name='bound_cards')
    op.drop_index(op.f('ix_bound_cards_bind_transaction_id'), table_name='bound_cards')
    op.drop_table('bound_cards')
    # ### end Alembic commands ###
